apiVersion: fn.kpt.dev/v1alpha1
kind: ApplySetters
metadata:
  name: inline-setters-spec
  annotations:
    config.kubernetes.io/local-config: true
setters:
  # These work like traditional ConfigMap-based apply-setters function-config
  data:
    bar: valueBar2
    baz: valueBaz2

  # These references resources, and reads from a field path and turns read
  # data into a setters value . This is similar to the
  # apply-replacements KRM function.
  references:

  - setterName: setter1          # Use the value from source below as setter with this name
    source:
      kind: Deployment           # A resource to locate
      name: my-nginx
      fieldPath: spec.replicas   # Read this field from resource

  - setterName: setter2
    source:
      kind: Kptfile
      fieldPath: upstream.git.ref
