name: Build and sign multi-arch container

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'Makefile.test'
      - 'scripts/**'
      - 'docs/**'
      - 'examples/**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Build schema bundle for kubeconform
      run: |
        scripts/source-schemas.sh

    - name: Build containers
      run: make all-container

    - name: Log in to the Container registry
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push containers
      run: make manifest-list | tee manifest.log

    # - name: Container meta
    #   id: meta
    #   run: |
    #     # manifest-list outputs digest last
    #     DIGEST=$(cat manifest.log | tail -n1 | grep 'Digest:' | cut -c9- | cut -d' ' -f1)
    #     echo "digest=$DIGEST" >> $GITHUB_OUTPUT
    #     GITSHA=$(make version | tail -n1)
    #     echo "sha=$GITSHA" >> $GITHUB_OUTPUT
    #     IMAGE=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')
    #     echo "image=$IMAGE@$DIGEST" >> $GITHUB_OUTPUT

    - uses: sigstore/cosign-installer@c56c2d3e59e4281cc41dea2217323ba5694b171e # tag=v3.8.0

    - name: Sign container
      run: make manifest-list-sign

    # - name: Verify signature
    #   run: cosign verify --certificate-identity 'https://github.com/${{ github.repository }}/.github/workflows/build.yaml@refs/heads/main' --certificate-oidc-issuer https://token.actions.githubusercontent.com ${{ needs.build.outputs.image }}
